[Unit]
Name = "desktop"
Description = "everything I need to work on Windows"
Requires = ["taskbar-toggle", "yasb", "komorebi"]

[Service]
Kind = "Oneshot"
Autostart = true
Restart = "Never"

[Service.ExecStart]
Executable = "cmd.exe"
Arguments = ["/c echo Running in the background..."]
